// Generated by CoffeeScript 1.6.3
var admins, express, unauthorized;

express = require('express');

admins = {
  nick: {
    role: 'admin',
    password: 'battleship'
  },
  anthony: {
    role: 'admin',
    password: 'battleship'
  }
};

unauthorized = function(res, realm) {
  res.statusCode = 401;
  res.setHeader('WWW-Authenticate', "Basic realm=\"" + realm + "\"'");
  return res.end('Unauthorized');
};

module.exports = function(realm) {
  if (realm == null) {
    realm = 'Authorization Required';
  }
  return function(req, res, next) {
    var a, credentials, index, parts, pass, user;
    if (req.admin_user) {
      return next();
    }
    if (!req.headers.authorization) {
      return unauthorized(res, realm);
    }
    parts = req.headers.authorization.split(' ');
    if (parts.length !== 2) {
      return next(400);
    }
    credentials = new Buffer(parts[1], 'base64').toString();
    index = credentials.indexOf(':');
    if (parts[0] !== 'Basic' || index < 0) {
      return next(400);
    }
    user = credentials.slice(0, index);
    pass = credentials.slice(index + 1);
    a = admins[user];
    if (!(a && a.password === pass)) {
      return unauthorized(res, realm);
    }
    req.admin_user = a;
    return next();
  };
};
