// Generated by CoffeeScript 1.6.3
var Driver, moment;

Driver = require('../models/driver');

moment = require('moment');

module.exports = function(req, res, next) {
  if (req.session && req.session.driver_id) {
    return Driver.findById(req.session.driver_id, function(err, driver) {
      if (err || (driver == null)) {
        req.session.driver_id = null;
        return res.send(500, err || 'Driver not found.');
      }
      req.driver = driver;
      if ((req.driver.last_activity == null) || moment().diff(moment(req.driver.last_activity)) > 1000 * 60 * 20) {
        req.driver.last_activity = new Date();
        return req.driver.save(next);
      } else {
        return next();
      }
    });
  } else {
    return next();
  }
};
