// Generated by CoffeeScript 1.6.3
var RedisStore, app, express, mongoose, util;

express = require('express');

mongoose = require('mongoose');

RedisStore = require('connect-redis')(express);

util = require('util');

mongoose.connect('mongodb://localhost/acmepedicabs');

mongoose.connection.on('error', function(err) {
  return console.log('mongoose error: ', err);
});

app = express();

app.use('/', express["static"]('static'));

app.use('/api', express.bodyParser());

app.use('/api', express.cookieParser());

app.use('/api', express.session({
  store: new RedisStore(),
  key: 's',
  secret: '234987dfghjkq2d39807231ojksdfcjhn3w47869324879'
}));

app.use('/api', require('./middleware/authn'));

require('./api/drivers')(app);

require('./api/fares')(app);

app.use(app.router);

if ('development' === app.get('env')) {
  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
}

if ('production' === app.get('env')) {
  app.use(express.errorHandler());
}

module.exports = require('http').createServer(app);
