// Generated by CoffeeScript 1.6.3
var DRIVER_STATES, compare_document, driver, moment, mongoose;

mongoose = require('mongoose');

moment = require('moment');

compare_document = require('../util').compare_document;

DRIVER_STATES = ['ready', 'dispatched', 'active', 'offline'];

driver = new mongoose.Schema({
  state: {
    type: String,
    "enum": DRIVER_STATES
  },
  name: {
    type: String,
    trim: true
  },
  email: {
    type: String,
    trim: true
  },
  location: [Number],
  created: {
    type: Date,
    "default": function() {
      return new Date();
    }
  }
});

driver.index({
  location: '2dsphere'
});

module.exports = mongoose.model('driver', driver);
