// Generated by CoffeeScript 1.6.3
var DRIVER_STATES, compare_document, driver, moment, mongoose;

mongoose = require('mongoose');

moment = require('moment');

compare_document = require('../util').compare_document;

DRIVER_STATES = ['ready', 'dispatched', 'active', 'offline'];

driver = new mongoose.Schema({
  state: {
    type: String,
    "enum": DRIVER_STATES
  },
  name: {
    type: String,
    trim: true
  },
  email: {
    type: String,
    trim: true
  },
  mobile: {
    type: String,
    trim: true
  },
  location: [Number],
  fare: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'fare'
  },
  created: {
    type: Date,
    "default": function() {
      return new Date();
    }
  },
  last_activity: {
    type: Date
  }
});

driver.index({
  location: '2dsphere'
});

driver.statics.findOnline = function(next) {
  return this.where('last_activity').gte(moment().add(-60 * 4, 'm')).exec(next);
};

module.exports = mongoose.model('driver', driver);
