// Generated by CoffeeScript 1.6.3
var FARE_STATES, compare_document, fare, moment, mongoose;

mongoose = require('mongoose');

moment = require('moment');

compare_document = require('../util').compare_document;

FARE_STATES = ['submitted', 'expired', 'dispatched', 'active', 'complete', 'canceled'];

fare = new mongoose.Schema({
  state: {
    type: String,
    "enum": FARE_STATES,
    "default": 'submitted'
  },
  name: {
    type: String,
    trim: true
  },
  location: [Number],
  created: {
    type: Date,
    "default": function() {
      return new Date();
    }
  },
  dispatched: {
    type: Date
  },
  pickedup: {
    type: Date
  },
  completed: {
    type: Date
  },
  canceled: {
    type: Date
  }
});

fare.index({
  location: '2dsphere'
});

module.exports = mongoose.model('fare', fare);

module.exports.STATE = FARE_STATES;
